name: sim_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - jupyter
  - pot
  - pandas
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - pip:
    - networkx==3.2.1
